"""empty message

Revision ID: 36e69f733ad4
Revises: 93f505eb5157
Create Date: 2019-03-02 14:46:10.218125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e69f733ad4'
down_revision = '93f505eb5157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'review_date')
    # ### end Alembic commands ###
