"""empty message

Revision ID: 8c146bd32c10
Revises: b6588f7dea0a
Create Date: 2019-03-03 16:18:18.270542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c146bd32c10'
down_revision = 'b6588f7dea0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_book_isbn', table_name='reviews')
    op.drop_constraint('reviews_reader_id_key', 'reviews', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('reviews_reader_id_key', 'reviews', ['reader_id'])
    op.create_index('ix_reviews_book_isbn', 'reviews', ['book_isbn'], unique=False)
    # ### end Alembic commands ###
