"""empty message

Revision ID: 93f505eb5157
Revises: dec07687f695
Create Date: 2019-03-02 12:48:41.748007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f505eb5157'
down_revision = 'dec07687f695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_isbn', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=1), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_isbn'], ['books.isbn'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_reviews_book_isbn'), 'reviews', ['book_isbn'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.drop_constraint('users_books_reviewed_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'books_reviewed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('books_reviewed', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_foreign_key('users_books_reviewed_fkey', 'users', 'books', ['books_reviewed'], ['isbn'])
    op.create_index('ix_users_username', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_reviews_book_isbn'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
