"""empty message

Revision ID: b6588f7dea0a
Revises: 
Create Date: 2019-03-03 14:42:03.249888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6588f7dea0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('author', sa.String(length=60), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_table('readers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readers_email'), 'readers', ['email'], unique=True)
    op.create_index(op.f('ix_readers_first_name'), 'readers', ['first_name'], unique=False)
    op.create_index(op.f('ix_readers_last_name'), 'readers', ['last_name'], unique=False)
    op.create_table('association',
    sa.Column('reader_id', sa.Integer(), nullable=True),
    sa.Column('book_isbn', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['book_isbn'], ['books.isbn'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], )
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.String(length=1), nullable=False),
    sa.Column('review_title', sa.String(), nullable=True),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.Column('book_isbn', sa.String(length=20), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_isbn'], ['books.isbn'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reader_id')
    )
    op.create_index(op.f('ix_reviews_book_isbn'), 'reviews', ['book_isbn'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_book_isbn'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('association')
    op.drop_index(op.f('ix_readers_last_name'), table_name='readers')
    op.drop_index(op.f('ix_readers_first_name'), table_name='readers')
    op.drop_index(op.f('ix_readers_email'), table_name='readers')
    op.drop_table('readers')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
