"""empty message

Revision ID: b6a52943108a
Revises: 
Create Date: 2019-03-01 09:35:49.468150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a52943108a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('books_reviewed', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('books_reviewed', name='users_books_reviewed_key'),
    sa.UniqueConstraint('password_hash', name='users_password_hash_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('isbn', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='books_pkey'),
    sa.UniqueConstraint('isbn', name='books_isbn_key')
    )
    # ### end Alembic commands ###
