"""empty message

Revision ID: e2a71075bbcf
Revises: 93f505eb5157
Create Date: 2019-03-02 15:08:40.456451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a71075bbcf'
down_revision = '93f505eb5157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.DateTime(), nullable=False),
    sa.Column('book_isbn', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=1), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_isbn'], ['books.isbn'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_reviews_book_isbn'), 'reviews', ['book_isbn'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_book_isbn'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
